name: "Bug report"
description: Create a report to help us fix your issue
body:
- type: markdown
  attributes:
    value: |
      **Is this the right place for my bug report?**
      This repository contains the Linux kernel used on the Raspberry Pi.
      If you believe that the issue you are seeing is kernel-related, this is the right place.
      If not, we have other repositories for the GPU firmware at [github.com/raspberrypi/firmware](https://github.com/raspberrypi/firmware) and Raspberry Pi userland applications at [github.com/raspberrypi/userland](https://github.com/raspberrypi/userland).
      
      If you have problems with the Raspbian distribution packages, report them in the [github.com/RPi-Distro/repo](https://github.com/RPi-Distro/repo).
      If you simply have a question, then [the Raspberry Pi forums](https://www.raspberrypi.org/forums) are the best place to ask it.

- type: textarea
  id: description
  attributes:
    label: Describe the bug
    description: |
      Add a clear and concise description of what you think the bug is.
  validations:
    required: true

- type: textarea
  id: reproduce
  attributes:
    label: Steps to reproduce the behaviour
    description: |
      List the steps required to reproduce the issue.
  validations:
    required: true

type: dropdown
  id: model
  attributes:
    label: Version
    description: On which device you are facing the bug?
    multiple: true
    options:
      - label: Raspberry Pi Zero
      - label: Raspberry Pi Zero W / WH
      - label: Raspberry Pi Zero 2 W
      - label: Raspberry Pi 1 Mod. A
      - label: Raspberry Pi 1 Mod. A+
      - label: Raspberry Pi 1 Mod. B
      - label: Raspberry Pi 1 Mod. B+
      - label: Raspberry Pi 2 Mod. B
      - label: Raspberry Pi 2 Mod. B v1.2
      - label: Raspberry Pi 3 Mod. A+
      - label: Raspberry Pi 3 Mod. B
      - label: Raspberry Pi 3 Mod. B+
      - label: Raspberry Pi 4 Mod. B
      - label: Raspberry Pi 400
      - label: Raspberry Pi CM1
      - label: Raspberry Pi CM3
      - label: Raspberry Pi CM3 Lite
      - label: Raspberry Pi CM3+
      - label: Raspberry Pi CM3+ Lite
      - label: Raspberry Pi CM4
      - label: Other
  validations:
    required: true

- type: textarea
  id: system
  attributes:
    label: System
    description: |
      Copy and paste the results of the raspinfo command in to this section.
      Alternatively, copy and paste a pastebin link, or add answers to the following questions:
      * Which OS and version (`cat /etc/rpi-issue`)?
      * Which firmware version (`vcgencmd version`)?
      * Which kernel version (`uname -a`)?
  validations:
    required: true

- type: textarea
  id: logs
  attributes:
    label: Logs
    description: |
      If applicable, add the relevant output from `dmesg` or similar.

- type: textarea
  id: additional
  attributes:
    label: Additional context
    description: |
      Add any other relevant context for the problem.

